name: rmd17
molecule_name: benzene

npz_path: ../../../datasets/rmd17/npz_data/rmd17_${dataset.molecule_name}.npz

load_data_function:
  _target_: GPR_MLIP.data.load_from_npz
  npz_path: ${dataset.npz_path}
  coordinates_key: ${dataset.coordinates_key}
  energy_key: energies
  representation_fn: ${representation.function}
  calc_representation: ${method.kernel.calc_representation}
  unit: kcal/mol

coordinates_key: coords
charges_key: nuclear_charges
